//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalKampus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KampusEntities : DbContext
    {
        public KampusEntities()
            : base("name=KampusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mahasiswa> Mahasiswas { get; set; }
        public virtual DbSet<MataKuliah> MataKuliahs { get; set; }
        public virtual DbSet<Seminar> Seminars { get; set; }
    }
}
