//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalKampus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        public string NRP { get; set; }
        public int IDMataKuliah { get; set; }
        public int IDSeminar { get; set; }
        public Nullable<int> mahasiswa_semester { get; set; }
        public string mahasiswa_nama { get; set; }
        public string mahasiswa_jurusan { get; set; }
        public string mahasiswa_alamat { get; set; }
    
        public virtual MataKuliah MataKuliah { get; set; }
        public virtual Seminar Seminar { get; set; }
    }
}
