//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalKampus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MataKuliah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MataKuliah()
        {
            this.Mahasiswas = new HashSet<Mahasiswa>();
        }
    
        public int matakuliah_id { get; set; }
        public string matakuliah_nama { get; set; }
        public Nullable<int> matakuliah_semester { get; set; }
        public Nullable<int> matakuliah_harga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mahasiswa> Mahasiswas { get; set; }
    }
}
